on:
  push:
    branches: [ main ]
  repository_dispatch:
    branches: [ main ]
  workflow_dispatch:
    branches: [ main ]

name: 🚀 Deploy website on push
jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Deploy FTP
        uses: SamKirkland/FTP-Deploy-Action@4.2.0
        with:
          server: ${{ secrets.UNILAB_FTP_SERVER }}
          username: ${{ secrets.UNILAB_FTP_USERNAME }}
          password: ${{ secrets.UNILAB_FTP_PASSWORD }}
          protocol: ${{ secrets.UNILAB_FTP_PROTOCOL }}
          port: ${{ secrets.UNILAB_FTP_PORT}}
          server-dir: ${{ secrets.UNILAB_FTP_REMOTE_ROOT }}
          local-dir: ./out/
          dangerous-clean-slate: false